### ISSUE TITLE
load does not decrypt from export 

### ISSUE THREAD

**Issue by Havivw** [nir0s/ghost#103]
flow:
  ghost export
  ghost init (on new machine)
  mv passphrase.ghost to /home/centos/.ghost/passphrases/haviv
  ghost load <export-file>  new-stash -p new-stash

error:
ghost get -s /home/centos/.ghost/cloudify.json[haviv] -p $(cat /home/centos/.ghost/passphrases/haviv) aws
STDOUT: Stash: tinydb at /home/centos/.ghost/cloudify.json[haviv]

STDERR: Traceback (most recent call last):
  File "/usr/bin/ghost", line 11, in <module>
    load_entry_point('ghost==0.5.0', 'console_scripts', 'ghost')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ghost.py", line 1237, in get_key
    record = stash.get(key_name=key_name, decrypt=not no_decrypt)
  File "/usr/lib/python2.7/site-packages/ghost.py", line 262, in get
    key['value'] = self._decrypt(key['value'])
  File "/usr/lib/python2.7/site-packages/ghost.py", line 449, in _decrypt
    encrypted_value).decode('ascii')
  File "/usr/lib64/python2.7/site-packages/cryptography/fernet.py", line 103, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken

**Comment by nir0s** [comment]
Yup, when loading it doesn't get both the passphrase requires for decrypting and encrypting. Will fix this.
