### ISSUE TITLE
Failure when providing a local path for a stash

### ISSUE THREAD

**Issue by nir0s** [nir0s/ghost#27]
running `ghost init stash.json` results in an error:

```bash
$ ghost init stash.json
Initializing stash...
Traceback (most recent call last):
  File "/home/nir0s/.virtualenvs/ghost/bin/ghost", line 11, in <module>
    load_entry_point('ghost', 'console_scripts', 'ghost')()
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nir0s/repos/nir0s/ghost/ghost.py", line 700, in init_stash
    passphrase = stash.init()
  File "/home/nir0s/repos/nir0s/ghost/ghost.py", line 145, in init
    self._storage.init()
  File "/home/nir0s/repos/nir0s/ghost/ghost.py", line 318, in init
    os.makedirs(os.path.dirname(self.db_path))
  File "/home/nir0s/.virtualenvs/ghost/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```

This happens because we're trying to create a directory for the stash path's base, which doesn't exist.

**Comment by nir0s** [comment]
Fixed for both SQLAlchemy and TinyDB storage
